Rearranged the way files are staged to temp to make it possible to monkey patch the venv files.

diff --git a/bin/venv2docker b/bin/venv2docker
--- a/bin/venv2docker
+++ b/bin/venv2docker
@@ -5,7 +5,7 @@
 # environment and installed dependencies.
 
 version="0.0.1"
-venv_root="${HOME}/.virtualenvs/"
+venv_root="${VIRTUALENVWRAPPER_HOOK_DIR}/"
 image_name=
 tag="latest"
 venv=
@@ -128,13 +128,9 @@ ensure_docker() {
 # check to be sure we were passed a valid venv, otherwise detect
 # the current active venv, set venv to the full path to the environment
 ensure_venv() {
-    target_venv="$venv"
-    if [ ! -z "${target_venv}" ]; then
-        path="${venv_root}${target_venv}"
-        if [ -d "${path}" ]; then
-            venv=$path
-        else
-            echo "Error: virtual env '${target_venv}' not found at ${venv_root}"
+    if [ ! -z "${venv}" ]; then
+        if [ ! -d "${venv_root}${venv}" ]; then
+            echo "Error: virtual env '${venv}' not found at ${venv_root}"
             exit 1
         fi
     else
@@ -144,18 +140,17 @@ ensure_venv() {
             echo
             show_help 1
         else
-            venv=$VIRTUAL_ENV
+            venv=$(basename ${VIRTUAL_ENV})
         fi
     fi
     # get the project directory from the virtualenv
-    projectpath=$(cat ${venv}/.project)
+    projectpath=$(cat ${venv_root}${venv}/${VIRTUALENVWRAPPER_PROJECT_FILENAME})
     if [ -z "${projectpath}" ]; then
         echo "Error: could not find project home for env $venv"
         exit 1
     fi
     path_split=($(echo ${projectpath} | tr "/" "\n"))
     projectdir=${path_split[ ${#path_split[@]} -1 ]}
-    unset target_venv
     unset path_split
 }
 
@@ -245,35 +240,82 @@ clean_build() {
     fi
 }
 
+# expects a directory path in $1, patches any text file in the
+# directory and subdirectories that contains the hard-coded
+# virtualenv interpreter path
+patch_paths() {
+    echo "Not yet"
+}
+
+# expects a directory path in $1, folder name in $2, tmp dir name in
+# $3, archive name in $4, stages the folder in temp, patches the paths, and
+# then zips it into the build directory.
+process_venv_directory() {
+    local base_dir=${1}
+    local venv_dir=${2}
+    local tmp_dir=${3}
+    local zip_name=${4}
+
+    echo "Staging ${base_dir}${venv_dir} to ${tmp_dir} ..."
+    if $( tar -c --directory=${base_dir} ./${venv_dir} --exclude=*.pyc | tar -x --directory=${tmp_dir} ); then
+        patch_paths ${tmp_dir}/${venv_dir}
+        echo "Packing ${tmp_dir}/${venv_dir} to ${projectpath}/${dockerdir} ..."
+        if $(tar -c --directory=${tmp_dir} ./${venv_dir} | gzip > ${projectpath}/${dockerdir}/${zip_name}.tar.gz); then
+            echo "${base_dir}${venv_dir} complete"
+            echo "Removing temporary files ..."
+            if $(rm -rf ${tmp_dir}/${venv_dir}); then
+                echo "Temporary files in ${tmp_dir}/${venv_dir} removed"
+            else
+                echo "Warning: unable to remove staging folder ${tmp_dir}/${venv_dir}"
+            fi
+        else
+            echo "Error: failed to pack ${tmp_dir}/${venv_dir}; check directory and file permissions."
+            exit 1
+        fi
+    else
+        echo "Error: failed to copy ${base_dir}/${venv_dir} to ${tmp_dir}; check directory and file permissions."
+        exit 1
+    fi
+}
+
 # stage the project directories to tmp, create the docker directory, and then
 # pack the project and system files into the docker directory.
 setup_build() {
-    # stage the project files in tmp
+    tmpdir=$(mktemp -d)
+
+    # if the build folder exists clean it out, this may remove the folder
+    # but will not if the user has copied anything to it, so we still
+    # use --exclude on the tar command below
+    if [ -d "${projectpath}/${dockerdir}" ]; then
+        clean_build
+    fi
+
+    # stage the project files in tmp - we check for the project path because
+    # its at least possible it might not exist, and that all the user wants
+    # is the virtualenv
     if [ -d "${projectpath}" ]; then
-        tmpdir=$(mktemp -d)
-        mkdir ${tmpdir}/${projectdir}
         echo "Staging ${projectpath} to ${tmpdir} ..."
-        if $(cp -R ${projectpath}/* ${tmpdir}/${projectdir}); then
+        if $( tar -c --directory=${projectpath} ../${projectdir} --exclude=*.pyc --exclude=./${projectdir}/${dockerdir} | tar -x --directory=${tmpdir} ); then
             echo "${projectpath} complete"
         else
-            echo "Error: failed to copy ${projectpath} to ${tmpdir}/${projectdir}; check directory and file permissions."
+            echo "Error: failed to copy ${projectpath} to ${tmpdir}; check directory and file permissions."
             exit 1
         fi
     else
         echo "Warning: ${projectpath} not found; skipping"
     fi
 
-    # create the build folder if we don't have it, otherwise run
-    # clean on it
-    if [ -d "${projectpath}/${dockerdir}" ]; then
-        clean_build
+    # create the build folder if we don't have it
+    if [ ! -d "${projectpath}/${dockerdir}" ]; then
+        echo "Creating build directory ..."
+        mkdir ${projectpath}/${dockerdir}
     fi
-    echo "Creating build directory ..."
-    mkdir ${projectpath}/${dockerdir}
 
+    # if we didn't skip the project files above then this path exists, so pack it
+    # into the build folder
     if [ -d "${tmpdir}/${projectdir}" ]; then
         echo "Packing project files ..."
-        if $(tar cfP - ${tmpdir}/${projectdir} --exclude=*.pyc | gzip > ${projectpath}/${dockerdir}/${projectdir}.tar.gz); then
+        if $(tar -c --directory=${tmpdir} ./${projectdir} | gzip > ${projectpath}/${dockerdir}/${projectdir}.tar.gz); then
             echo "${tmpdir}/${projectdir} complete"
         else
             echo "Error: failed to pack ${tmpdir}/${projectdir}; check directory and file permissions."
@@ -288,49 +330,33 @@ setup_build() {
     fi
 
     echo "Packing system files ..."
-    if [ -d "${venv}/bin" ]; then
-        if $(tar cfP - ${venv}/bin --exclude=*.pyc | gzip > ${projectpath}/${dockerdir}/venv_bin.tar.gz); then
-            echo "${venv}/bin complete"
-        else
-            echo "Error: failed to pack ${venv}/bin; check directory and file permissions."
-            exit 1
-        fi
+
+    if [ -d "${venv_root}${venv}/bin" ]; then
+        process_venv_directory ${venv_root} ${venv}/bin ${tmpdir} venv_bin
     else
-        echo "Warning: ${venv}/bin not found; skipping"
+        echo "Warning: ${venv_root}${venv}/bin not found; skipping"
     fi
 
-    if [ -d "${venv}/lib" ]; then
-        if $(tar cfP - ${venv}/lib --exclude=*.pyc | gzip > ${projectpath}/${dockerdir}/venv_lib.tar.gz); then
-            echo "${venv}/lib complete"
-        else
-            echo "Error: failed to pack ${venv}/lib; check directory and file permissions."
-            exit 1
-        fi
+    if [ -d "${venv_root}${venv}/include" ]; then
+        process_venv_directory ${venv_root} ${venv}/include ${tmpdir} venv_include
     else
-        echo "Warning: ${venv}/lib not found; skipping"
+        echo "Warning: ${venv_root}${venv}/include not found; skipping"
     fi
 
-    if [ -d "${venv}/include" ]; then
-        if $(tar cfP - ${venv}/include  --exclude=*.pyc | gzip > ${projectpath}/${dockerdir}/venv_include.tar.gz); then
-            echo "${venv}/include complete"
-        else
-            echo "Error: failed to pack ${venv}/include; check directory and file permissions."
-            exit 1
-        fi
+    if [ -d "${venv_root}${venv}/lib" ]; then
+        process_venv_directory ${venv_root} ${venv}/lib ${tmpdir} venv_lib
     else
-        echo "Warning: ${venv}/include not found; skipping"
+        echo "Warning: ${venv_root}${venv}/lib not found; skipping"
     fi
 
-    if [ -d "${venv}/local/lib" ]; then
-        if $(tar cfP - ${venv}/local/lib --exclude=*.pyc | gzip > ${projectpath}/${dockerdir}/venv_local_lib.tar.gz); then
-            echo "${venv}/local/lib complete"
-        else
-            echo "Error: failed to pack ${venv}/local/lib; check directory and file permissions."
-            exit 1
-        fi
+    if [ -d "${venv_root}${venv}/local/lib" ]; then
+        process_venv_directory ${venv_root} ${venv}/local/lib ${tmpdir} venv_local_lib
     else
-        echo "Warning: ${venv}/local/lib not found; skipping"
+        echo "Warning: ${venv_root}${venv}/local/lib not found; skipping"
     fi
+
+    echo "Removing temporary directory ..."
+    rm -rf ${tmpdir}
     echo "System files completed"
 }
 
@@ -422,30 +448,30 @@ emit_dockerfile_install_commands() {
     if [ -f "${projectdir}.tar.gz" ]; then
         echo "Adding ${projectdir}.tar.gz"
         dockerfile+=("COPY ${projectdir}.tar.gz ${bin_path}")
-        dockerfile+=("RUN cd ${bin_path} && tar xfz ${projectdir}.tar.gz --strip-components=2")
+        dockerfile+=("RUN cd ${bin_path} && tar xfz ${projectdir}.tar.gz && rm ${projectdir}.tar.gz")
         sys_paths+=("${bin_path}${projectdir}")
         python_paths+=("${bin_path}${projectdir}")
     fi
     if [ -f "venv_bin.tar.gz" ]; then
         echo "Adding venv_bin.tar.gz"
         dockerfile+=("COPY venv_bin.tar.gz ${lib_path}")
-        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_bin.tar.gz --strip-components=3 && rm venv_bin.tar.gz")
+        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_bin.tar.gz && rm venv_bin.tar.gz")
         sys_paths+=("${lib_path}${projectdir}/bin")
     fi
     if [ -f "venv_include.tar.gz" ]; then
         echo "Adding venv_include.tar.gz"
         dockerfile+=("COPY venv_include.tar.gz ${lib_path}")
-        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_include.tar.gz --strip-components=3 && rm venv_include.tar.gz")
+        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_include.tar.gz && rm venv_include.tar.gz")
     fi
     if [ -f "venv_lib.tar.gz" ]; then
         echo "Adding venv_lib.tar.gz"
         dockerfile+=("COPY venv_lib.tar.gz ${lib_path}")
-        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_lib.tar.gz --strip-components=3 && rm venv_lib.tar.gz")
+        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_lib.tar.gz && rm venv_lib.tar.gz")
     fi
     if [ -f "venv_local_lib.tar.gz" ]; then
         echo "Adding venv_local_lib.tar.gz"
         dockerfile+=("COPY venv_local_lib.tar.gz ${lib_path}")
-        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_local_lib.tar.gz --strip-components=3 && rm venv_local_lib.tar.gz")
+        dockerfile+=("RUN cd ${lib_path} && tar xfz venv_local_lib.tar.gz && rm venv_local_lib.tar.gz")
     fi
 }
 
